import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

async function checkQuizzes() {
  console.log('🔍 Checking course_quizzes table...\n');

  // Get all quizzes with course info
  const { data: quizzes, error } = await supabase
    .from('course_quizzes')
    .select('course_id, questions, metadata');

  if (error) {
    console.error('❌ Error fetching quizzes:', error);
    process.exit(1);
  }

  if (!quizzes || quizzes.length === 0) {
    console.log('❌ No quizzes found in course_quizzes table!');
    console.log('\nThe table is empty. You need to run: npm run generate-quizzes');
    process.exit(0);
  }

  console.log(`✅ Found ${quizzes.length} quizzes:\n`);

  // Get course titles
  const { data: courses } = await supabase
    .from('courses')
    .select('id, title');

  const courseMap = new Map(courses?.map(c => [c.id, c.title]) || []);

  quizzes.forEach(quiz => {
    const courseTitle = courseMap.get(quiz.course_id) || 'Unknown Course';
    const numQuestions = quiz.questions?.length || 0;
    const generatedBy = quiz.metadata?.generated_by || 'unknown';
    console.log(`- ${courseTitle}`);
    console.log(`  Course ID: ${quiz.course_id}`);
    console.log(`  Questions: ${numQuestions}`);
    console.log(`  Generated by: ${generatedBy}`);
    console.log('');
  });

  console.log('✅ All quizzes are in the database!');
}

checkQuizzes();
