// Complete shop data: 280+ items (140 themes + 140 avatars)
// 20 items per rarity tier per type

const themeData = {
  common: [
    { name: 'Azure Mist', colors: ['#3b82f6', '#1e40af', '#f0f9ff'], icon: '🌫️', desc: 'Soft blue fog rolling through calm landscapes', price: 0 },
    { name: 'Calm Waters', colors: ['#0ea5e9', '#0284c7', '#f0fdfa'], icon: '🌊', desc: 'Peaceful blue ocean on a still morning', price: 25 },
    { name: 'Simple Slate', colors: ['#64748b', '#475569', '#f8fafc'], icon: '🪨', desc: 'Clean gray minimal design', price: 25 },
    { name: 'Mint Breeze', colors: ['#10b981', '#059669', '#f0fdf4'], icon: '🌿', desc: 'Fresh green wind across open fields', price: 25 },
    { name: 'Lavender Fields', colors: ['#a78bfa', '#8b5cf6', '#faf5ff'], icon: '💜', desc: 'Purple flowers swaying gently', price: 25 },
    { name: 'Peach Fuzz', colors: ['#fb923c', '#f97316', '#fff7ed'], icon: '🍑', desc: 'Warm orange and pink tones', price: 25 },
    { name: 'Sky Blue', colors: ['#7dd3fc', '#0ea5e9', '#f0f9ff'], icon: '☁️', desc: 'Clear day atmosphere', price: 25 },
    { name: 'Forest Floor', colors: ['#65a30d', '#4d7c0f', '#f7fee7'], icon: '🌲', desc: 'Mossy earth tones', price: 25 },
    { name: 'Rose Garden', colors: ['#f9a8d4', '#ec4899', '#fdf2f8'], icon: '🌹', desc: 'Soft pink floral beauty', price: 25 },
    { name: 'Ocean Spray', colors: ['#2dd4bf', '#14b8a6', '#f0fdfa'], icon: '💧', desc: 'Light teal sea foam', price: 25 },
    { name: 'Sunny Meadow', colors: ['#facc15', '#eab308', '#fefce8'], icon: '🌻', desc: 'Bright yellow happiness', price: 35 },
    { name: 'Cloud White', colors: ['#f1f5f9', '#e2e8f0', '#ffffff'], icon: '☁️', desc: 'Pure soft minimalism', price: 35 },
    { name: 'Berry Blast', colors: ['#f87171', '#ef4444', '#fef2f2'], icon: '🍓', desc: 'Mixed fruit red tones', price: 35 },
    { name: 'River Stone', colors: ['#94a3b8', '#64748b', '#f8fafc'], icon: '🪨', desc: 'Smooth gray-blue rocks', price: 35 },
    { name: 'Leafy Green', colors: ['#4ade80', '#22c55e', '#f0fdf4'], icon: '🍃', desc: 'Fresh nature vibes', price: 35 },
    { name: 'Coral Reef', colors: ['#fb7185', '#f43f5e', '#fff1f2'], icon: '🪸', desc: 'Tropical underwater colors', price: 35 },
    { name: 'Twilight Blue', colors: ['#818cf8', '#6366f1', '#eef2ff'], icon: '🌆', desc: 'Evening sky gradient', price: 40 },
    { name: 'Autumn Leaf', colors: ['#fb923c', '#ea580c', '#fff7ed'], icon: '🍂', desc: 'Orange brown warmth', price: 40 },
    { name: 'Crystal Clear', colors: ['#e0f2fe', '#bae6fd', '#f0f9ff'], icon: '💎', desc: 'Transparent beauty', price: 40 },
    { name: 'Starlight', colors: ['#e2e8f0', '#cbd5e1', '#f8fafc'], icon: '✨', desc: 'Subtle silver glow', price: 50 },
  ],
  uncommon: [
    { name: 'Emerald Forest', colors: ['#10b981', '#059669', '#064e3b'], icon: '🌲', desc: 'Deep green woodland sanctuary', price: 75 },
    { name: 'Sunrise Glow', colors: ['#fbbf24', '#f59e0b', '#fef3c7'], icon: '🌅', desc: 'Golden morning light breaking', price: 75 },
    { name: 'Copper Dreams', colors: ['#ea580c', '#c2410c', '#fff7ed'], icon: '🧡', desc: 'Warm metallic orange elegance', price: 75 },
    { name: 'Arctic Frost', colors: ['#67e8f9', '#06b6d4', '#ecfeff'], icon: '❄️', desc: 'Crisp blue ice crystals', price: 75 },
    { name: 'Violet Valley', colors: ['#8b5cf6', '#7c3aed', '#f5f3ff'], icon: '🏔️', desc: 'Purple mountain majesty', price: 75 },
    { name: 'Golden Sands', colors: ['#fbbf24', '#d97706', '#fefce8'], icon: '🏜️', desc: 'Desert warmth and peace', price: 75 },
    { name: 'Ruby Sunset', colors: ['#ef4444', '#dc2626', '#fef2f2'], icon: '🌇', desc: 'Deep red evening skies', price: 75 },
    { name: 'Ocean Depths', colors: ['#1e40af', '#1e3a8a', '#eff6ff'], icon: '🌊', desc: 'Dark blue underwater mystery', price: 75 },
    { name: 'Jade Jungle', colors: ['#059669', '#047857', '#f0fdf4'], icon: '🌴', desc: 'Lush tropical paradise', price: 85 },
    { name: 'Amber Glow', colors: ['#f59e0b', '#d97706', '#fffbeb'], icon: '🟡', desc: 'Warm fossilized light', price: 85 },
    { name: 'Sapphire Storm', colors: ['#3b82f6', '#2563eb', '#eff6ff'], icon: '⚡', desc: 'Electric blue energy', price: 85 },
    { name: 'Plum Paradise', colors: ['#a855f7', '#9333ea', '#faf5ff'], icon: '🍇', desc: 'Rich purple elegance', price: 85 },
    { name: 'Cherry Blossom', colors: ['#f9a8d4', '#ec4899', '#fdf2f8'], icon: '🌸', desc: 'Pink spring serenity', price: 85 },
    { name: 'Bronze Beauty', colors: ['#d97706', '#b45309', '#fffbeb'], icon: '🥉', desc: 'Metallic warm sophistication', price: 90 },
    { name: 'Teal Tranquility', colors: ['#14b8a6', '#0d9488', '#f0fdfa'], icon: '🧘', desc: 'Calm blue-green balance', price: 90 },
    { name: 'Silver Moon', colors: ['#e2e8f0', '#cbd5e1', '#f8fafc'], icon: '🌙', desc: 'Cool metallic night', price: 90 },
    { name: 'Coral Kingdom', colors: ['#fb7185', '#f43f5e', '#fff1f2'], icon: '🪸', desc: 'Vibrant underwater realm', price: 90 },
    { name: 'Lime Light', colors: ['#84cc16', '#65a30d', '#f7fee7'], icon: '💚', desc: 'Bright citrus energy', price: 100 },
    { name: 'Indigo Night', colors: ['#6366f1', '#4f46e5', '#eef2ff'], icon: '🌌', desc: 'Deep purple sky', price: 100 },
    { name: 'Rose Gold', colors: ['#fb7185', '#f43f5e', '#fff1f2'], icon: '🌹', desc: 'Elegant pink metal', price: 100 },
  ],
  rare: [
    { name: 'Deep Ocean Kingdom', colors: ['#1e40af', '#1e3a8a', '#0f172a'], icon: '🌊', desc: 'Underwater empire depths', price: 200 },
    { name: 'Solar Flare Haven', colors: ['#fbbf24', '#f59e0b', '#451a03'], icon: '☀️', desc: 'Sun sanctuary realm', price: 200 },
    { name: 'Twilight Garden', colors: ['#a855f7', '#7c3aed', '#2e1065'], icon: '🌆', desc: 'Dusk enchanted gardens', price: 200 },
    { name: 'Crystal Frost', colors: ['#67e8f9', '#0891b2', '#164e63'], icon: '❄️', desc: 'Ice crystal paradise', price: 200 },
    { name: 'Volcanic Core', colors: ['#dc2626', '#b91c1c', '#450a0a'], icon: '🌋', desc: 'Magma center depths', price: 200 },
    { name: 'Mystic Forest', colors: ['#166534', '#14532d', '#052e16'], icon: '🌲', desc: 'Ancient enchanted woods', price: 220 },
    { name: 'Aurora Skies', colors: ['#06b6d4', '#8b5cf6', '#1e1b4b'], icon: '🌌', desc: 'Northern lights heavens', price: 220 },
    { name: 'Desert Mirage', colors: ['#d97706', '#b45309', '#78350f'], icon: '🏜️', desc: 'Sand illusion realm', price: 220 },
    { name: 'Thunder Valley', colors: ['#6366f1', '#4f46e5', '#312e81'], icon: '⚡', desc: 'Storm canyon domain', price: 220 },
    { name: 'Coral Empire', colors: ['#f43f5e', '#e11d48', '#881337'], icon: '🪸', desc: 'Reef kingdom depths', price: 220 },
    { name: 'Shadow Realm', colors: ['#475569', '#1e293b', '#0f172a'], icon: '🌑', desc: 'Dark dimension void', price: 240 },
    { name: 'Golden Prairie', colors: ['#facc15', '#ca8a04', '#422006'], icon: '🌾', desc: 'Wheat field expanse', price: 240 },
    { name: 'Glacier Peaks', colors: ['#bae6fd', '#0ea5e9', '#0c4a6e'], icon: '🏔️', desc: 'Ice mountain range', price: 240 },
    { name: 'Plasma Fields', colors: ['#f97316', '#ea580c', '#7c2d12'], icon: '💫', desc: 'Energy plasma lands', price: 240 },
    { name: 'Jade Sanctuary', colors: ['#10b981', '#059669', '#064e3b'], icon: '🏯', desc: 'Sacred green temple', price: 240 },
    { name: 'Ruby Fortress', colors: ['#ef4444', '#dc2626', '#991b1b'], icon: '🏰', desc: 'Red castle stronghold', price: 250 },
    { name: 'Sapphire Depths', colors: ['#3b82f6', '#2563eb', '#1e3a8a'], icon: '💎', desc: 'Blue ocean trenches', price: 250 },
    { name: 'Amber Mines', colors: ['#f59e0b', '#d97706', '#78350f'], icon: '⛏️', desc: 'Fossil treasure caves', price: 250 },
    { name: 'Emerald City', colors: ['#22c55e', '#16a34a', '#14532d'], icon: '🏙️', desc: 'Green metropolis', price: 250 },
    { name: 'Diamond Peaks', colors: ['#e0f2fe', '#7dd3fc', '#0284c7'], icon: '💠', desc: 'Crystal mountain spires', price: 250 },
  ],
  epic: [
    { name: 'Nebula Edge', colors: ['#7c3aed', '#6d28d9', '#1e1b4b'], icon: '🌌', desc: 'Cosmic boundary realm', price: 350 },
    { name: 'Crystal Nexus', colors: ['#a855f7', '#9333ea', '#2e1065'], icon: '💎', desc: 'Prismatic convergence point', price: 350 },
    { name: 'Volcanic Heart', colors: ['#dc2626', '#b91c1c', '#0a0a0a'], icon: '🌋', desc: 'Magma core chamber', price: 350 },
    { name: 'Aurora Palace', colors: ['#06b6d4', '#8b5cf6', '#0f172a'], icon: '🏰', desc: 'Northern lights citadel', price: 350 },
    { name: 'Phoenix Flame', colors: ['#fb923c', '#f97316', '#431407'], icon: '🔥', desc: 'Eternal fire sanctuary', price: 350 },
    { name: 'Storm Forge', colors: ['#6366f1', '#4f46e5', '#1e1b4b'], icon: '⚡', desc: 'Lightning creation space', price: 380 },
    { name: 'Ocean Throne', colors: ['#0369a1', '#075985', '#082f49'], icon: '👑', desc: 'Deep sea dominion', price: 380 },
    { name: 'Forest Spirit', colors: ['#16a34a', '#15803d', '#052e16'], icon: '🌳', desc: 'Ancient woodland consciousness', price: 380 },
    { name: 'Crystal Dimension', colors: ['#e0f2fe', '#7dd3fc', '#0369a1'], icon: '🔮', desc: 'Prismatic reality', price: 380 },
    { name: 'Shadow Citadel', colors: ['#1f2937', '#111827', '#000000'], icon: '🏴', desc: 'Dark fortress stronghold', price: 380 },
    { name: 'Solar Sanctum', colors: ['#fbbf24', '#f59e0b', '#451a03'], icon: '🌞', desc: 'Sun power temple', price: 400 },
    { name: 'Lunar Haven', colors: ['#e2e8f0', '#94a3b8', '#475569'], icon: '🌙', desc: 'Moonlight refuge', price: 400 },
    { name: 'Thunder Peak', colors: ['#818cf8', '#6366f1', '#312e81'], icon: '🏔️', desc: 'Storm summit domain', price: 400 },
    { name: 'Plasma Core', colors: ['#f97316', '#ea580c', '#1e1b4b'], icon: '☢️', desc: 'Energy reactor center', price: 400 },
    { name: 'Mystic Grove', colors: ['#a855f7', '#7c3aed', '#2e1065'], icon: '🌿', desc: 'Enchanted nature realm', price: 400 },
    { name: 'Inferno Depths', colors: ['#ef4444', '#dc2626', '#0a0a0a'], icon: '🔥', desc: 'Burning underworld', price: 450 },
    { name: 'Glacier Kingdom', colors: ['#67e8f9', '#06b6d4', '#164e63'], icon: '❄️', desc: 'Frozen empire lands', price: 450 },
    { name: 'Desert Oasis', colors: ['#fbbf24', '#d97706', '#92400e'], icon: '🏝️', desc: 'Paradise spring refuge', price: 450 },
    { name: 'Cosmic Wave', colors: ['#c084fc', '#a855f7', '#1e1b4b'], icon: '🌊', desc: 'Space energy flow', price: 450 },
    { name: 'Elemental Rift', colors: ['#f97316', '#3b82f6', '#10b981'], icon: '🌀', desc: 'All elements converge', price: 500 },
  ],
  legendary: [
    { name: 'Phoenix Dominion', colors: ['#fb923c', '#f97316', '#431407'], icon: '🔥', desc: 'Rising from ashes empire', price: 600 },
    { name: 'Aurora Sky Palace', colors: ['#06b6d4', '#8b5cf6', '#1e1b4b'], icon: '🏰', desc: 'Northern lights citadel', price: 600 },
    { name: 'Dragonfire Sanctuary', colors: ['#dc2626', '#b91c1c', '#0a0a0a'], icon: '🐉', desc: 'Ancient dragon realm', price: 600 },
    { name: 'Celestial Horizon', colors: ['#c084fc', '#a855f7', '#2e1065'], icon: '🌌', desc: 'Heavenly boundary view', price: 600 },
    { name: 'Time Weaver Domain', colors: ['#a855f7', '#6366f1', '#1e1b4b'], icon: '⏳', desc: 'Temporal mastery space', price: 650 },
    { name: 'Void Between Stars', colors: ['#1f2937', '#111827', '#000000'], icon: '🌑', desc: 'Cosmic darkness void', price: 650 },
    { name: 'Genesis Garden', colors: ['#22c55e', '#16a34a', '#052e16'], icon: '🌱', desc: 'Life creation paradise', price: 650 },
    { name: 'Storm King Peak', colors: ['#6366f1', '#4f46e5', '#312e81'], icon: '⚡', desc: 'Lightning ruler throne', price: 650 },
    { name: 'Ocean Emperor Realm', colors: ['#0369a1', '#075985', '#082f49'], icon: '👑', desc: 'Deep sea dominion', price: 700 },
    { name: 'Flame Heart Citadel', colors: ['#ef4444', '#dc2626', '#450a0a'], icon: '🔥', desc: 'Eternal fire fortress', price: 700 },
    { name: 'Crystal Oracle', colors: ['#e0f2fe', '#7dd3fc', '#0369a1'], icon: '🔮', desc: 'Prismatic prophecy temple', price: 700 },
    { name: 'Shadow Monarch Tomb', colors: ['#1f2937', '#111827', '#000000'], icon: '🦇', desc: 'Dark ruler sanctuary', price: 750 },
    { name: 'Solar Phoenix Nest', colors: ['#fbbf24', '#f59e0b', '#451a03'], icon: '☀️', desc: 'Sun birth sanctuary', price: 750 },
    { name: 'Lunar Eclipse Void', colors: ['#64748b', '#475569', '#1e293b'], icon: '🌑', desc: 'Moon shadow realm', price: 750 },
    { name: 'Thunder God Arena', colors: ['#818cf8', '#6366f1', '#1e3a8a'], icon: '🏛️', desc: 'Storm lord battlefield', price: 800 },
    { name: 'Inferno Dragon Lair', colors: ['#dc2626', '#b91c1c', '#0a0a0a'], icon: '🐲', desc: 'Fire beast domain', price: 800 },
    { name: 'Glacier Titan Palace', colors: ['#67e8f9', '#06b6d4', '#164e63'], icon: '🏔️', desc: 'Ice giant stronghold', price: 850 },
    { name: 'Cosmic Serpent Coil', colors: ['#c084fc', '#a855f7', '#1e1b4b'], icon: '🐍', desc: 'Space dragon realm', price: 850 },
    { name: 'Elemental Chaos Vortex', colors: ['#f97316', '#3b82f6', '#10b981'], icon: '🌀', desc: 'Pure energy storm', price: 900 },
    { name: 'Eternal Flame Throne', colors: ['#fbbf24', '#f59e0b', '#7c2d12'], icon: '👑', desc: 'Forever fire seat', price: 1000 },
  ],
  mythical: [
    { name: 'Celestial Being Realm', colors: ['#fbbf24', '#f472b6', '#1e1b4b'], icon: '✨', desc: 'Higher entity domain', price: 1200, premium: true },
    { name: 'Void Emperor Palace', colors: ['#1f2937', '#000000', '#000000'], icon: '🌑', desc: 'Master of void throne', price: 1300 },
    { name: 'Quantum Deity Sanctum', colors: ['#a855f7', '#6366f1', '#1e1b4b'], icon: '⚛️', desc: 'God of quantum temple', price: 1400 },
    { name: 'Titans Wrath Arena', colors: ['#dc2626', '#fbbf24', '#1e1b4b'], icon: '⚡', desc: 'Powerful titan battlefield', price: 1500 },
    { name: 'Primordial Cosmos', colors: ['#c084fc', '#fbbf24', '#1e1b4b'], icon: '🌌', desc: 'Ancient universe birthplace', price: 1600 },
    { name: 'Reality Shaper Void', colors: ['#8b5cf6', '#06b6d4', '#0f172a'], icon: '🌀', desc: 'Shape existence dimension', price: 1700 },
    { name: 'Eternal Watcher Peak', colors: ['#e2e8f0', '#64748b', '#1e293b'], icon: '👁️', desc: 'All-seeing summit', price: 1800 },
    { name: 'Alpha Omega Nexus', colors: ['#fbbf24', '#1f2937', '#000000'], icon: '♾️', desc: 'Beginning and end point', price: 1900 },
    { name: 'Supreme Creator Haven', colors: ['#ffd700', '#fbbf24', '#0a0a0a'], icon: '👑', desc: 'Divine architect sanctuary', price: 2000 },
    { name: 'The Absolute Void', colors: ['#ffffff', '#000000', '#000000'], icon: '🌌', desc: 'Ultimate nothingness', price: 2000, premium: true },
    // Add 10 more mythical
    { name: 'Cosmic Ascension Gate', colors: ['#c084fc', '#a855f7', '#1e1b4b'], icon: '🚪', desc: 'Transcendent portal', price: 1500 },
    { name: 'Dream Reality Prism', colors: ['#f0abfc', '#e879f9', '#2e1065'], icon: '💫', desc: 'Surreal dimension lens', price: 1600 },
    { name: 'Inferno Core Throne', colors: ['#ef4444', '#dc2626', '#0a0a0a'], icon: '🔥', desc: 'Magma ruler seat', price: 1700 },
    { name: 'Divine Light Sanctuary', colors: ['#fef3c7', '#fde68a', '#1c1917'], icon: '☀️', desc: 'Radiant holy ground', price: 1800 },
    { name: 'Astral Plane Gateway', colors: ['#a855f7', '#9333ea', '#0f172a'], icon: '🌟', desc: 'Higher dimension entrance', price: 1900 },
    { name: 'Nebula Dreamscape', colors: ['#f472b6', '#ec4899', '#831843'], icon: '☁️', desc: 'Cosmic fantasy realm', price: 2000, premium: true },
    { name: 'Solar Flare Empire', colors: ['#fbbf24', '#f59e0b', '#451a03'], icon: '🌞', desc: 'Intense sun dominion', price: 1500 },
    { name: 'Plasma Storm Domain', colors: ['#f97316', '#ea580c', '#7c2d12'], icon: '💥', desc: 'High energy territory', price: 1600 },
    { name: 'Phoenix Rebirth Nest', colors: ['#fb923c', '#f97316', '#431407'], icon: '🔥', desc: 'Rising flame sanctuary', price: 1700 },
    { name: 'Timeless Space Continuum', colors: ['#8b5cf6', '#7c3aed', '#1e1b4b'], icon: '⏰', desc: 'Eternal cosmos flow', price: 1800 },
  ],
  godly: [
    { name: 'Genesis Point Origin', colors: ['#ffd700', '#ffed4e', '#0a0a0a'], icon: '🌟', desc: 'Creation birth moment', price: 2500, premium: true },
    { name: 'Eternal Void Throne', colors: ['#000000', '#000000', '#000000'], icon: '👑', desc: 'Absolute darkness seat', price: 2600, premium: true },
    { name: 'Cosmic Heart Pulse', colors: ['#fbbf24', '#f472b6', '#0f172a'], icon: '💖', desc: 'Universe life center', price: 2700, premium: true },
    { name: 'Reality Bender Apex', colors: ['#ff0000', '#ff7f00', '#000000'], icon: '🌀', desc: 'Bend existence peak', price: 2800, premium: true },
    { name: 'Universal Mind Hive', colors: ['#ff6b6b', '#feca57', '#000000'], icon: '🧠', desc: 'Cosmic consciousness', price: 2900, premium: true },
    { name: 'Creator Essence Source', colors: ['#ffd700', '#ffed4e', '#0a0a0a'], icon: '✨', desc: 'Maker fundamental power', price: 3000, premium: true },
    { name: 'Absolute Infinity Edge', colors: ['#ffffff', '#ffffff', '#000000'], icon: '♾️', desc: 'Endless boundary', price: 3200, premium: true },
    { name: 'Omega Alpha Merge', colors: ['#fbbf24', '#1f2937', '#000000'], icon: '☯️', desc: 'Start and end unite', price: 3400, premium: true },
    { name: 'Eternal Phoenix Nest', colors: ['#fbbf24', '#dc2626', '#0a0a0a'], icon: '🔥', desc: 'Forever rebirth place', price: 3600, premium: true },
    { name: 'Supreme Architect Throne', colors: ['#ffd700', '#fbbf24', '#1e1b4b'], icon: '👑', desc: 'Ultimate creator seat', price: 4000, premium: true },
    { name: 'Divine Prism Palace', colors: ['#f472b6', '#06b6d4', '#8b5cf6'], icon: '💎', desc: 'Holy rainbow fortress', price: 3000, premium: true },
    { name: 'Transcendent Gate', colors: ['#fbbf24', '#ffffff', '#1e1b4b'], icon: '🚪', desc: 'Beyond mortal portal', price: 3200, premium: true },
    { name: 'Infinite Cosmos Core', colors: ['#c084fc', '#1e1b4b', '#000000'], icon: '🌌', desc: 'Endless space center', price: 3400, premium: true },
    { name: 'Quantum Singularity', colors: ['#a855f7', '#ffffff', '#000000'], icon: '⚛️', desc: 'All matter collapse point', price: 3600, premium: true },
    { name: 'Celestial Zenith', colors: ['#fbbf24', '#f472b6', '#1e1b4b'], icon: '⭐', desc: 'Highest heavens peak', price: 3800, premium: true },
    { name: 'Primordial Chaos', colors: ['#f97316', '#3b82f6', '#10b981'], icon: '🌀', desc: 'Before order void', price: 4000, premium: true },
    { name: 'Eternal Watch Eye', colors: ['#e2e8f0', '#64748b', '#1e293b'], icon: '👁️', desc: 'All-seeing forever gaze', price: 4200, premium: true },
    { name: 'Alpha Reality', colors: ['#ffffff', '#fbbf24', '#1e1b4b'], icon: '🌟', desc: 'First existence truth', price: 4400, premium: true },
    { name: 'Omega Finality', colors: ['#000000', '#1f2937', '#000000'], icon: '💀', desc: 'Last ending moment', price: 4600, premium: true },
    { name: 'The Absolute One', colors: ['#ffffff', '#000000', '#1e1b4b'], icon: '✨', desc: 'Single unity being', price: 5000, premium: true },
  ],
};

const avatarData = {
  common: [
    { name: 'Nova Spark', category: 'science', icon: '⚡', desc: 'Energetic beginner scientist', price: 0 },
    { name: 'Jett Riley', category: 'discovery', icon: '🔭', desc: 'Curious young explorer', price: 25 },
    { name: 'Luna-5', category: 'technology', icon: '🤖', desc: 'Helpful lab robot assistant', price: 25 },
    { name: 'Kai Zen', category: 'study', icon: '🧘', desc: 'Focused meditation student', price: 25 },
    { name: 'Zara Prime', category: 'space', icon: '🌟', desc: 'Enthusiastic astronomy fan', price: 25 },
    { name: 'Max Flux', category: 'chemistry', icon: '⚗️', desc: 'Dynamic chemistry learner', price: 25 },
    { name: 'Aria Byte', category: 'technology', icon: '💻', desc: 'Tech-savvy coder', price: 25 },
    { name: 'Rio Storm', category: 'earth', icon: '⛈️', desc: 'Passionate weather tracker', price: 25 },
    { name: 'Piper Glow', category: 'biology', icon: '🧬', desc: 'Bright biology student', price: 25 },
    { name: 'Echo Vector', category: 'physics', icon: '📐', desc: 'Quiet math genius', price: 25 },
    { name: 'Sage Wild', category: 'biology', icon: '🌿', desc: 'Nature-loving researcher', price: 35 },
    { name: 'Dart Nova', category: 'science', icon: '🎯', desc: 'Quick-thinking experimenter', price: 35 },
    { name: 'Quinn Sky', category: 'space', icon: '🔭', desc: 'Dreamy telescope observer', price: 35 },
    { name: 'Fern Moss', category: 'biology', icon: '🌱', desc: 'Patient botany student', price: 35 },
    { name: 'Clay Earth', category: 'earth', icon: '🪨', desc: 'Grounded geology fan', price: 35 },
    { name: 'Blaze Ray', category: 'physics', icon: '☀️', desc: 'Energetic physics student', price: 35 },
    { name: 'Ginger Spice', category: 'chemistry', icon: '🧪', desc: 'Zesty chemistry mixer', price: 40 },
    { name: 'Onyx Stone', category: 'science', icon: '⚫', desc: 'Stoic researcher', price: 40 },
    { name: 'Ivy League', category: 'academia', icon: '📚', desc: 'Ambitious scholar', price: 40 },
    { name: 'Cobalt Blue', category: 'chemistry', icon: '🔵', desc: 'Steady lab partner', price: 50 },
  ],
  uncommon: [
    { name: 'Orion Void', category: 'space', icon: '🌌', desc: 'Space exploration specialist', price: 75 },
    { name: 'Astra Neo', category: 'space', icon: '⭐', desc: 'Star mapping enthusiast', price: 75 },
    { name: 'Phoenix Ray', category: 'science', icon: '🔥', desc: 'Resilient experimenter', price: 75 },
    { name: 'Echo Vector', category: 'physics', icon: '🔊', desc: 'Sound wave researcher', price: 75 },
    { name: 'Ion Storm', category: 'physics', icon: '⚡', desc: 'Electricity prodigy', price: 75 },
    { name: 'Flux Core', category: 'physics', icon: '💫', desc: 'Energy manipulation expert', price: 75 },
    { name: 'Nova X-7', category: 'technology', icon: '🤖', desc: 'Advanced robotics engineer', price: 75 },
    { name: 'Zara Prime', category: 'physics', icon: '🔮', desc: 'Quantum computing whiz', price: 75 },
    { name: 'Kai Zen', category: 'physics', icon: '☯️', desc: 'Meditative physics master', price: 85 },
    { name: 'Luna Stellar', category: 'space', icon: '🌙', desc: 'Lunar geology specialist', price: 85 },
    { name: 'Max Flux', category: 'physics', icon: '🧲', desc: 'Magnetic field researcher', price: 85 },
    { name: 'Aria Byte', category: 'technology', icon: '🧠', desc: 'AI algorithm developer', price: 85 },
    { name: 'Rio Storm', category: 'earth', icon: '🌪️', desc: 'Weather prediction expert', price: 85 },
    { name: 'Piper Glow', category: 'biology', icon: '✨', desc: 'Bioluminescence researcher', price: 90 },
    { name: 'Sage Wild', category: 'biology', icon: '🌿', desc: 'Ecosystem analyst', price: 90 },
    { name: 'Dart Nova', category: 'physics', icon: '💥', desc: 'Plasma physics pioneer', price: 90 },
    { name: 'Quinn Sky', category: 'earth', icon: '☁️', desc: 'Atmospheric scientist', price: 90 },
    { name: 'Fern Moss', category: 'biology', icon: '🧬', desc: 'Botanical genetics expert', price: 100 },
    { name: 'Clay Earth', category: 'earth', icon: '🌋', desc: 'Seismic activity monitor', price: 100 },
    { name: 'Blaze Ray', category: 'physics', icon: '☀️', desc: 'Solar energy researcher', price: 100 },
  ],
  rare: [
    { name: 'Quantum Zara', category: 'physics', icon: '⚛️', desc: 'Quantum mechanics expert', price: 200 },
    { name: 'Cyber Kai', category: 'technology', icon: '💾', desc: 'Cybernetics researcher', price: 200 },
    { name: 'Luna Stellar', category: 'space', icon: '🌙', desc: 'Lunar colony director', price: 200 },
    { name: 'Orion Flux', category: 'space', icon: '🌟', desc: 'Stellar cartographer', price: 200 },
    { name: 'Phoenix Ray', category: 'chemistry', icon: '🔥', desc: 'Thermodynamics specialist', price: 200 },
    { name: 'Ion Storm', category: 'physics', icon: '⚡', desc: 'Particle accelerator expert', price: 220 },
    { name: 'Neon Glow', category: 'physics', icon: '💡', desc: 'Light physicist', price: 220 },
    { name: 'Titan Forge', category: 'technology', icon: '🔧', desc: 'Engineering mastermind', price: 220 },
    { name: 'Atlas Core', category: 'earth', icon: '🌍', desc: 'Geological surveyor', price: 220 },
    { name: 'Zephyr Wind', category: 'earth', icon: '🌬️', desc: 'Atmospheric dynamics', price: 240 },
    { name: 'Crystal Joy', category: 'biology', icon: '🔬', desc: 'Crystallography expert', price: 240 },
    { name: 'Botanical Blaze', category: 'biology', icon: '🌺', desc: 'Exotic botanist', price: 240 },
    { name: 'Mars Vanguard', category: 'space', icon: '🚀', desc: 'Mars mission leader', price: 240 },
    { name: 'Comet Chase', category: 'space', icon: '☄️', desc: 'Comet tracker', price: 240 },
    { name: 'Solar Flare', category: 'physics', icon: '🌞', desc: 'Solar physicist', price: 250 },
    { name: 'Lunar Tide', category: 'space', icon: '🌊', desc: 'Tidal researcher', price: 250 },
    { name: 'Quantum Leap', category: 'physics', icon: '🔄', desc: 'Quantum computing', price: 250 },
    { name: 'Bio Spark', category: 'biology', icon: '⚗️', desc: 'Biochemistry genius', price: 250 },
    { name: 'Tech Nova', category: 'technology', icon: '🖥️', desc: 'Systems architect', price: 250 },
    { name: 'Data Dream', category: 'technology', icon: '💭', desc: 'Big data analyst', price: 250 },
  ],
  epic: [
    { name: 'Nebula Stormborn', category: 'space', icon: '🌌', desc: 'Cosmic energy being', price: 350 },
    { name: 'Cosmic Jett', category: 'space', icon: '✨', desc: 'Interstellar navigator', price: 350 },
    { name: 'Stellar Astra', category: 'space', icon: '⭐', desc: 'Star system mapper', price: 350 },
    { name: 'Quantum Phoenix', category: 'physics', icon: '🔥', desc: 'Resurrection physicist', price: 350 },
    { name: 'Void Orion', category: 'space', icon: '🌑', desc: 'Black hole explorer', price: 350 },
    { name: 'Galactic Zen', category: 'space', icon: '🧘', desc: 'Cosmic meditation master', price: 380 },
    { name: 'Celestial Vector', category: 'physics', icon: '💫', desc: 'Light speed researcher', price: 380 },
    { name: 'Aurora Prime', category: 'earth', icon: '🌌', desc: 'Northern lights expert', price: 380 },
    { name: 'Cosmic Ray', category: 'physics', icon: '☀️', desc: 'Radiation specialist', price: 380 },
    { name: 'Eclipse Nova', category: 'space', icon: '🌑', desc: 'Shadow astronomer', price: 380 },
    { name: 'Plasma Storm', category: 'physics', icon: '⚡', desc: 'Energy field master', price: 400 },
    { name: 'Frost Flame', category: 'chemistry', icon: '❄️', desc: 'Cryothermics expert', price: 400 },
    { name: 'Thunder Strike', category: 'physics', icon: '🌩️', desc: 'Electricity master', price: 400 },
    { name: 'Crystal Wave', category: 'biology', icon: '💎', desc: 'Mineral biologist', price: 400 },
    { name: 'Nature Wrath', category: 'biology', icon: '🌪️', desc: 'Elemental biologist', price: 400 },
    { name: 'Tech Titan', category: 'technology', icon: '🤖', desc: 'Machine consciousness', price: 450 },
    { name: 'Data Sage', category: 'technology', icon: '📊', desc: 'Algorithm seer', price: 450 },
    { name: 'Nano Spark', category: 'technology', icon: '🔬', desc: 'Nanotechnology pioneer', price: 450 },
    { name: 'Quantum Dream', category: 'physics', icon: '💭', desc: 'Reality theorist', price: 500 },
    { name: 'Cosmic Mind', category: 'space', icon: '🧠', desc: 'Universal consciousness', price: 500 },
  ],
  legendary: [
    { name: 'Eternal Stellar', category: 'space', icon: '⭐', desc: 'Timeless star dweller', price: 600 },
    { name: 'Infinite Zara', category: 'physics', icon: '♾️', desc: 'Boundless energy master', price: 600 },
    { name: 'Transcendent Kai', category: 'science', icon: '✨', desc: 'Beyond matter being', price: 600 },
    { name: 'Ascended Orion', category: 'space', icon: '🚀', desc: 'Higher dimensional traveler', price: 600 },
    { name: 'Cosmic Luna', category: 'space', icon: '🌙', desc: 'Celestial satellite goddess', price: 650 },
    { name: 'Omega Nova', category: 'physics', icon: '💥', desc: 'Final explosion entity', price: 650 },
    { name: 'Alpha Zenith', category: 'science', icon: '🔝', desc: 'Peak knowledge holder', price: 650 },
    { name: 'Eternal Phoenix', category: 'chemistry', icon: '🔥', desc: 'Forever rebirth alchemist', price: 650 },
    { name: 'Supreme Vector', category: 'physics', icon: '➡️', desc: 'Ultimate direction master', price: 700 },
    { name: 'Ultimate Cosmos', category: 'space', icon: '🌌', desc: 'All-space dweller', price: 700 },
    { name: 'Divine Spark', category: 'science', icon: '✨', desc: 'Creator fragment holder', price: 750 },
    { name: 'Infinite Storm', category: 'physics', icon: '🌪️', desc: 'Endless energy source', price: 750 },
    { name: 'Celestial Flame', category: 'chemistry', icon: '🔥', desc: 'Holy fire alchemist', price: 750 },
    { name: 'Quantum Apex', category: 'physics', icon: '⚛️', desc: 'Peak quantum master', price: 800 },
    { name: 'Stellar Prime', category: 'space', icon: '⭐', desc: 'First star entity', price: 800 },
    { name: 'Cosmic Wrath', category: 'space', icon: '💫', desc: 'Universe rage being', price: 850 },
    { name: 'Eternal Void', category: 'physics', icon: '🕳️', desc: 'Nothingness guardian', price: 850 },
    { name: 'Supreme Flame', category: 'chemistry', icon: '🔥', desc: 'Ultimate fire master', price: 900 },
    { name: 'Infinite Dream', category: 'science', icon: '💭', desc: 'Limitless imagination', price: 900 },
    { name: 'Cosmic Heart', category: 'space', icon: '💖', desc: 'Universe love spirit', price: 1000 },
  ],
  mythical: [
    { name: 'Eternal Stellar', category: 'divine', icon: '⭐', desc: 'Timeless celestial being', price: 1200, premium: true },
    { name: 'Infinite Zara', category: 'divine', icon: '♾️', desc: 'Boundless cosmic entity', price: 1300, premium: true },
    { name: 'Transcendent Kai', category: 'divine', icon: '✨', desc: 'Ascended beyond form', price: 1400, premium: true },
    { name: 'Ascended Orion', category: 'divine', icon: '🚀', desc: 'Higher realm traveler', price: 1500, premium: true },
    { name: 'Cosmic Luna', category: 'divine', icon: '🌙', desc: 'Moon goddess ascended', price: 1600, premium: true },
    { name: 'Omega Nova', category: 'divine', icon: '💥', desc: 'Final transformation being', price: 1700 },
    { name: 'Alpha Zenith', category: 'divine', icon: '🔝', desc: 'Supreme peak entity', price: 1800 },
    { name: 'Eternal Phoenix', category: 'divine', icon: '🔥', desc: 'Immortal fire spirit', price: 1900 },
    { name: 'Supreme Vector', category: 'divine', icon: '➡️', desc: 'Ultimate path master', price: 2000, premium: true },
    { name: 'Ultimate Cosmos', category: 'divine', icon: '🌌', desc: 'All-universe deity', price: 2000, premium: true },
    { name: 'Divine Nova', category: 'divine', icon: '✨', desc: 'Holy explosion being', price: 1500 },
    { name: 'Sacred Flame', category: 'divine', icon: '🔥', desc: 'Blessed fire spirit', price: 1600 },
    { name: 'Mystic Storm', category: 'divine', icon: '🌪️', desc: 'Enchanted tempest god', price: 1700 },
    { name: 'Celestial Zen', category: 'divine', icon: '🧘', desc: 'Heavenly meditation master', price: 1800 },
    { name: 'Quantum Sage', category: 'divine', icon: '⚛️', desc: 'Atomic wisdom keeper', price: 1900 },
    { name: 'Stellar Lord', category: 'divine', icon: '⭐', desc: 'Star realm ruler', price: 2000, premium: true },
    { name: 'Void Master', category: 'divine', icon: '🕳️', desc: 'Nothingness controller', price: 1500 },
    { name: 'Cosmic Dreamer', category: 'divine', icon: '💭', desc: 'Universe imagination', price: 1600 },
    { name: 'Eternal Wave', category: 'divine', icon: '🌊', desc: 'Forever energy flow', price: 1700 },
    { name: 'Supreme Zenith', category: 'divine', icon: '🔝', desc: 'Absolute peak being', price: 1800 },
  ],
  godly: [
    { name: 'Omega Nova', category: 'divine', icon: '💥', desc: 'Final supreme being', price: 2500, premium: true },
    { name: 'Alpha Zenith', category: 'divine', icon: '🔝', desc: 'First and last entity', price: 2600, premium: true },
    { name: 'Eternal Phoenix', category: 'divine', icon: '🔥', desc: 'Forever immortal bird', price: 2700, premium: true },
    { name: 'Supreme Vector', category: 'divine', icon: '➡️', desc: 'Ultimate reality arrow', price: 2800, premium: true },
    { name: 'Ultimate Cosmos', category: 'divine', icon: '🌌', desc: 'All existence lord', price: 2900, premium: true },
    { name: 'Genesis Spark', category: 'divine', icon: '✨', desc: 'Creation flame holder', price: 3000, premium: true },
    { name: 'Infinite Edge', category: 'divine', icon: '🔪', desc: 'Endless boundary blade', price: 3200, premium: true },
    { name: 'Absolute One', category: 'divine', icon: '1️⃣', desc: 'Single unity god', price: 3400, premium: true },
    { name: 'Eternal Flame', category: 'divine', icon: '🔥', desc: 'Never-ending fire', price: 3600, premium: true },
    { name: 'Supreme Architect', category: 'divine', icon: '🏗️', desc: 'Ultimate builder deity', price: 4000, premium: true },
    { name: 'Divine Creator', category: 'divine', icon: '👑', desc: 'God of all makers', price: 3000, premium: true },
    { name: 'Transcendent Gate', category: 'divine', icon: '🚪', desc: 'Beyond divine portal', price: 3200, premium: true },
    { name: 'Infinite Throne', category: 'divine', icon: '👑', desc: 'Endless ruling seat', price: 3400, premium: true },
    { name: 'Quantum God', category: 'divine', icon: '⚛️', desc: 'Atomic deity supreme', price: 3600, premium: true },
    { name: 'Celestial Supreme', category: 'divine', icon: '⭐', desc: 'Heavenly ultimate', price: 3800, premium: true },
    { name: 'Eternal Watcher', category: 'divine', icon: '👁️', desc: 'Forever seeing god', price: 4000, premium: true },
    { name: 'Alpha Reality', category: 'divine', icon: '🌟', desc: 'First truth lord', price: 4200, premium: true },
    { name: 'Omega Finality', category: 'divine', icon: '💀', desc: 'Last ending master', price: 4400, premium: true },
    { name: 'Cosmic Unity', category: 'divine', icon: '☯️', desc: 'All合一deity', price: 4600, premium: true },
    { name: 'The Absolute', category: 'divine', icon: '✨', desc: 'Ultimate supreme being', price: 5000, premium: true },
  ],
};

const rarityLevels = {
  common: { level: 1 },
  uncommon: { level: 5 },
  rare: { level: 10 },
  epic: { level: 20 },
  legendary: { level: 40 },
  mythical: { level: 60 },
  godly: { level: 100 },
};

export { themeData, avatarData, rarityLevels };
