-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 4: CAPACITORS AND DIELECTRICS
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 4.4.1: Capacitance Definition
UPDATE lessons
SET
    title = 'Capacitance Definition',
    slug = 'capacitance-definition',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.1", "content": "Comprehensive explanation of Capacitance Definition including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.1", "problem": "Practice problem demonstrating key principles of Capacitance Definition", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Capacitance Definition", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.1-uuid';

-- Lesson 4.4.2: Parallel Plate Capacitor
UPDATE lessons
SET
    title = 'Parallel Plate Capacitor',
    slug = 'parallel-plate-capacitor',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.2", "content": "Comprehensive explanation of Parallel Plate Capacitor including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.2", "problem": "Practice problem demonstrating key principles of Parallel Plate Capacitor", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Parallel Plate Capacitor", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.2-uuid';

-- Lesson 4.4.3: Cylindrical and Spherical Capacitors
UPDATE lessons
SET
    title = 'Cylindrical and Spherical Capacitors',
    slug = 'cylindrical-spherical-capacitors',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.3", "content": "Comprehensive explanation of Cylindrical and Spherical Capacitors including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.3", "problem": "Practice problem demonstrating key principles of Cylindrical and Spherical Capacitors", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Cylindrical and Spherical Capacitors", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.3-uuid';

-- Lesson 4.4.4: Capacitors in Parallel
UPDATE lessons
SET
    title = 'Capacitors in Parallel',
    slug = 'capacitors-parallel',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.4", "content": "Comprehensive explanation of Capacitors in Parallel including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.4", "problem": "Practice problem demonstrating key principles of Capacitors in Parallel", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Capacitors in Parallel", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.4-uuid';

-- Lesson 4.4.5: Capacitors in Series
UPDATE lessons
SET
    title = 'Capacitors in Series',
    slug = 'capacitors-series',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.5", "content": "Comprehensive explanation of Capacitors in Series including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.5", "problem": "Practice problem demonstrating key principles of Capacitors in Series", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Capacitors in Series", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.5-uuid';

-- Lesson 4.4.6: Energy Storage
UPDATE lessons
SET
    title = 'Energy Storage',
    slug = 'energy-storage-capacitors',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.6", "content": "Comprehensive explanation of Energy Storage including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.6", "problem": "Practice problem demonstrating key principles of Energy Storage", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Energy Storage", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.6-uuid';

-- Lesson 4.4.7: Dielectric Materials
UPDATE lessons
SET
    title = 'Dielectric Materials',
    slug = 'dielectric-materials',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.7", "content": "Comprehensive explanation of Dielectric Materials including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.7", "problem": "Practice problem demonstrating key principles of Dielectric Materials", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Dielectric Materials", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.7-uuid';

-- Lesson 4.4.8: Dielectric Constant
UPDATE lessons
SET
    title = 'Dielectric Constant',
    slug = 'dielectric-constant',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.8", "content": "Comprehensive explanation of Dielectric Constant including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.8", "problem": "Practice problem demonstrating key principles of Dielectric Constant", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Dielectric Constant", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.8-uuid';

-- Lesson 4.4.9: Polarization of Dielectrics
UPDATE lessons
SET
    title = 'Polarization of Dielectrics',
    slug = 'polarization-dielectrics',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.9", "content": "Comprehensive explanation of Polarization of Dielectrics including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.9", "problem": "Practice problem demonstrating key principles of Polarization of Dielectrics", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Polarization of Dielectrics", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.9-uuid';

-- Lesson 4.4.10: Applications of Capacitors
UPDATE lessons
SET
    title = 'Applications of Capacitors',
    slug = 'capacitors-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 4.4.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 4 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 4.4.10", "content": "Comprehensive explanation of Applications of Capacitors including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 4.4.10", "problem": "Practice problem demonstrating key principles of Applications of Capacitors", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications of Capacitors", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 4.4.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 4.4.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 4.4.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch4-l4.10-uuid';

-- =====================================================
-- END OF CHAPTER 4
-- =====================================================