-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 3: ELECTRIC POTENTIAL
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 3.3.1: Electric Potential Energy
UPDATE lessons
SET
    title = 'Electric Potential Energy',
    slug = 'electric-potential-energy',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.1", "content": "Comprehensive explanation of Electric Potential Energy including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.1", "problem": "Practice problem demonstrating key principles of Electric Potential Energy", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Potential Energy", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.1-uuid';

-- Lesson 3.3.2: Electric Potential Definition
UPDATE lessons
SET
    title = 'Electric Potential Definition',
    slug = 'electric-potential-definition',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.2", "content": "Comprehensive explanation of Electric Potential Definition including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.2", "problem": "Practice problem demonstrating key principles of Electric Potential Definition", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Potential Definition", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.2-uuid';

-- Lesson 3.3.3: Potential of Point Charges
UPDATE lessons
SET
    title = 'Potential of Point Charges',
    slug = 'potential-point-charges',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.3", "content": "Comprehensive explanation of Potential of Point Charges including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.3", "problem": "Practice problem demonstrating key principles of Potential of Point Charges", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Potential of Point Charges", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.3-uuid';

-- Lesson 3.3.4: Potential of Continuous Distributions
UPDATE lessons
SET
    title = 'Potential of Continuous Distributions',
    slug = 'potential-continuous-distributions',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.4", "content": "Comprehensive explanation of Potential of Continuous Distributions including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.4", "problem": "Practice problem demonstrating key principles of Potential of Continuous Distributions", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Potential of Continuous Distributions", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.4-uuid';

-- Lesson 3.3.5: Equipotential Surfaces
UPDATE lessons
SET
    title = 'Equipotential Surfaces',
    slug = 'equipotential-surfaces',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.5", "content": "Comprehensive explanation of Equipotential Surfaces including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.5", "problem": "Practice problem demonstrating key principles of Equipotential Surfaces", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Equipotential Surfaces", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.5-uuid';

-- Lesson 3.3.6: Potential Gradient
UPDATE lessons
SET
    title = 'Potential Gradient',
    slug = 'potential-gradient',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.6", "content": "Comprehensive explanation of Potential Gradient including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.6", "problem": "Practice problem demonstrating key principles of Potential Gradient", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Potential Gradient", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.6-uuid';

-- Lesson 3.3.7: Field-Potential Relationship
UPDATE lessons
SET
    title = 'Field-Potential Relationship',
    slug = 'field-potential-relationship',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.7", "content": "Comprehensive explanation of Field-Potential Relationship including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.7", "problem": "Practice problem demonstrating key principles of Field-Potential Relationship", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Field-Potential Relationship", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.7-uuid';

-- Lesson 3.3.8: Energy of Charge Systems
UPDATE lessons
SET
    title = 'Energy of Charge Systems',
    slug = 'energy-charge-systems',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.8", "content": "Comprehensive explanation of Energy of Charge Systems including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.8", "problem": "Practice problem demonstrating key principles of Energy of Charge Systems", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Energy of Charge Systems", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.8-uuid';

-- Lesson 3.3.9: Electrostatic Boundary Conditions
UPDATE lessons
SET
    title = 'Electrostatic Boundary Conditions',
    slug = 'electrostatic-boundary',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.9", "content": "Comprehensive explanation of Electrostatic Boundary Conditions including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.9", "problem": "Practice problem demonstrating key principles of Electrostatic Boundary Conditions", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electrostatic Boundary Conditions", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.9-uuid';

-- Lesson 3.3.10: Applications of Potential
UPDATE lessons
SET
    title = 'Applications of Potential',
    slug = 'potential-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 3.3.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 3 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 3.3.10", "content": "Comprehensive explanation of Applications of Potential including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 3.3.10", "problem": "Practice problem demonstrating key principles of Applications of Potential", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications of Potential", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 3.3.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 3.3.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 3.3.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch3-l3.10-uuid';

-- =====================================================
-- END OF CHAPTER 3
-- =====================================================