-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 6: DIRECT CURRENT CIRCUITS
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 6.6.1: Series Circuits
UPDATE lessons
SET
    title = 'Series Circuits',
    slug = 'series-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.1", "content": "Comprehensive explanation of Series Circuits including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.1", "problem": "Practice problem demonstrating key principles of Series Circuits", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Series Circuits", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.1-uuid';

-- Lesson 6.6.2: Parallel Circuits
UPDATE lessons
SET
    title = 'Parallel Circuits',
    slug = 'parallel-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.2", "content": "Comprehensive explanation of Parallel Circuits including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.2", "problem": "Practice problem demonstrating key principles of Parallel Circuits", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Parallel Circuits", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.2-uuid';

-- Lesson 6.6.3: Series-Parallel Combinations
UPDATE lessons
SET
    title = 'Series-Parallel Combinations',
    slug = 'series-parallel-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.3", "content": "Comprehensive explanation of Series-Parallel Combinations including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.3", "problem": "Practice problem demonstrating key principles of Series-Parallel Combinations", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Series-Parallel Combinations", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.3-uuid';

-- Lesson 6.6.4: Kirchhoff's Rules
UPDATE lessons
SET
    title = 'Kirchhoff's Rules',
    slug = 'kirchhoffs-rules',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.4", "content": "Comprehensive explanation of Kirchhoff''s Rules including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.4", "problem": "Practice problem demonstrating key principles of Kirchhoff''s Rules", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Kirchhoff''s Rules", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.4-uuid';

-- Lesson 6.6.5: RC Circuits
UPDATE lessons
SET
    title = 'RC Circuits',
    slug = 'rc-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.5", "content": "Comprehensive explanation of RC Circuits including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.5", "problem": "Practice problem demonstrating key principles of RC Circuits", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about RC Circuits", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.5-uuid';

-- Lesson 6.6.6: Time Constants
UPDATE lessons
SET
    title = 'Time Constants',
    slug = 'time-constants',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.6", "content": "Comprehensive explanation of Time Constants including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.6", "problem": "Practice problem demonstrating key principles of Time Constants", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Time Constants", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.6-uuid';

-- Lesson 6.6.7: Measuring Instruments
UPDATE lessons
SET
    title = 'Measuring Instruments',
    slug = 'measuring-instruments',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.7", "content": "Comprehensive explanation of Measuring Instruments including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.7", "problem": "Practice problem demonstrating key principles of Measuring Instruments", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Measuring Instruments", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.7-uuid';

-- Lesson 6.6.8: Wheat Dissipation
UPDATE lessons
SET
    title = 'Wheat Dissipation',
    slug = 'heat-dissipation',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.8", "content": "Comprehensive explanation of Wheat Dissipation including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.8", "problem": "Practice problem demonstrating key principles of Wheat Dissipation", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Wheat Dissipation", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.8-uuid';

-- Lesson 6.6.9: Complex Network Analysis
UPDATE lessons
SET
    title = 'Complex Network Analysis',
    slug = 'complex-networks',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.9", "content": "Comprehensive explanation of Complex Network Analysis including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.9", "problem": "Practice problem demonstrating key principles of Complex Network Analysis", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Complex Network Analysis", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.9-uuid';

-- Lesson 6.6.10: Practical Circuit Design
UPDATE lessons
SET
    title = 'Practical Circuit Design',
    slug = 'practical-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 6.6.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 6 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 6.6.10", "content": "Comprehensive explanation of Practical Circuit Design including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 6.6.10", "problem": "Practice problem demonstrating key principles of Practical Circuit Design", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Practical Circuit Design", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 6.6.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 6.6.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 6.6.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch6-l6.10-uuid';

-- =====================================================
-- END OF CHAPTER 6
-- =====================================================