-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 5: CURRENT AND RESISTANCE
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 5.5.1: Electric Current
UPDATE lessons
SET
    title = 'Electric Current',
    slug = 'electric-current',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.1", "content": "Comprehensive explanation of Electric Current including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.1", "problem": "Practice problem demonstrating key principles of Electric Current", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Current", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.1-uuid';

-- Lesson 5.5.2: Ohm's Law
UPDATE lessons
SET
    title = 'Ohm's Law',
    slug = 'ohms-law',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.2", "content": "Comprehensive explanation of Ohm''s Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.2", "problem": "Practice problem demonstrating key principles of Ohm''s Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Ohm''s Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.2-uuid';

-- Lesson 5.5.3: Resistance and Resistivity
UPDATE lessons
SET
    title = 'Resistance and Resistivity',
    slug = 'resistance-resistivity',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.3", "content": "Comprehensive explanation of Resistance and Resistivity including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.3", "problem": "Practice problem demonstrating key principles of Resistance and Resistivity", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Resistance and Resistivity", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.3-uuid';

-- Lesson 5.5.4: Temperature Dependence
UPDATE lessons
SET
    title = 'Temperature Dependence',
    slug = 'temperature-dependence',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.4", "content": "Comprehensive explanation of Temperature Dependence including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.4", "problem": "Practice problem demonstrating key principles of Temperature Dependence", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Temperature Dependence", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.4-uuid';

-- Lesson 5.5.5: Energy and Power in Circuits
UPDATE lessons
SET
    title = 'Energy and Power in Circuits',
    slug = 'energy-power-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.5", "content": "Comprehensive explanation of Energy and Power in Circuits including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.5", "problem": "Practice problem demonstrating key principles of Energy and Power in Circuits", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Energy and Power in Circuits", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.5-uuid';

-- Lesson 5.5.6: Superconductivity
UPDATE lessons
SET
    title = 'Superconductivity',
    slug = 'superconductivity',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.6", "content": "Comprehensive explanation of Superconductivity including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.6", "problem": "Practice problem demonstrating key principles of Superconductivity", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Superconductivity", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.6-uuid';

-- Lesson 5.5.7: Semiconductors
UPDATE lessons
SET
    title = 'Semiconductors',
    slug = 'semiconductors',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.7", "content": "Comprehensive explanation of Semiconductors including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.7", "problem": "Practice problem demonstrating key principles of Semiconductors", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Semiconductors", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.7-uuid';

-- Lesson 5.5.8: Non-Ohmic Devices
UPDATE lessons
SET
    title = 'Non-Ohmic Devices',
    slug = 'non-ohmic-devices',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.8", "content": "Comprehensive explanation of Non-Ohmic Devices including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.8", "problem": "Practice problem demonstrating key principles of Non-Ohmic Devices", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Non-Ohmic Devices", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.8-uuid';

-- Lesson 5.5.9: Microscopic View of Conduction
UPDATE lessons
SET
    title = 'Microscopic View of Conduction',
    slug = 'microscopic-conduction',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.9", "content": "Comprehensive explanation of Microscopic View of Conduction including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.9", "problem": "Practice problem demonstrating key principles of Microscopic View of Conduction", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Microscopic View of Conduction", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.9-uuid';

-- Lesson 5.5.10: Practical Circuit Elements
UPDATE lessons
SET
    title = 'Practical Circuit Elements',
    slug = 'practical-circuit-elements',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 5.5.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 5 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 5.5.10", "content": "Comprehensive explanation of Practical Circuit Elements including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 5.5.10", "problem": "Practice problem demonstrating key principles of Practical Circuit Elements", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Practical Circuit Elements", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 5.5.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 5.5.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 5.5.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch5-l5.10-uuid';

-- =====================================================
-- END OF CHAPTER 5
-- =====================================================