-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 10: MODERN ELECTROMAGNETISM AND OPTICS
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 10.10.1: Relativistic Electromagnetism
UPDATE lessons
SET
    title = 'Relativistic Electromagnetism',
    slug = 'relativistic-electromagnetism',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.1", "content": "Comprehensive explanation of Relativistic Electromagnetism including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.1", "problem": "Practice problem demonstrating key principles of Relativistic Electromagnetism", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Relativistic Electromagnetism", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.1-uuid';

-- Lesson 10.10.2: Fields of Moving Charges
UPDATE lessons
SET
    title = 'Fields of Moving Charges',
    slug = 'fields-moving-charges',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.2", "content": "Comprehensive explanation of Fields of Moving Charges including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.2", "problem": "Practice problem demonstrating key principles of Fields of Moving Charges", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Fields of Moving Charges", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.2-uuid';

-- Lesson 10.10.3: Electromagnetic Radiation
UPDATE lessons
SET
    title = 'Electromagnetic Radiation',
    slug = 'em-radiation',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.3", "content": "Comprehensive explanation of Electromagnetic Radiation including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.3", "problem": "Practice problem demonstrating key principles of Electromagnetic Radiation", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electromagnetic Radiation", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.3-uuid';

-- Lesson 10.10.4: Optical Phenomena
UPDATE lessons
SET
    title = 'Optical Phenomena',
    slug = 'optical-phenomena',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.4", "content": "Comprehensive explanation of Optical Phenomena including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.4", "problem": "Practice problem demonstrating key principles of Optical Phenomena", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Optical Phenomena", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.4-uuid';

-- Lesson 10.10.5: Interference
UPDATE lessons
SET
    title = 'Interference',
    slug = 'interference',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.5", "content": "Comprehensive explanation of Interference including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.5", "problem": "Practice problem demonstrating key principles of Interference", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Interference", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.5-uuid';

-- Lesson 10.10.6: Diffraction
UPDATE lessons
SET
    title = 'Diffraction',
    slug = 'diffraction',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.6", "content": "Comprehensive explanation of Diffraction including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.6", "problem": "Practice problem demonstrating key principles of Diffraction", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Diffraction", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.6-uuid';

-- Lesson 10.10.7: Geometrical Optics
UPDATE lessons
SET
    title = 'Geometrical Optics',
    slug = 'geometrical-optics',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.7", "content": "Comprehensive explanation of Geometrical Optics including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.7", "problem": "Practice problem demonstrating key principles of Geometrical Optics", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Geometrical Optics", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.7-uuid';

-- Lesson 10.10.8: Physical Optics
UPDATE lessons
SET
    title = 'Physical Optics',
    slug = 'physical-optics',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.8", "content": "Comprehensive explanation of Physical Optics including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.8", "problem": "Practice problem demonstrating key principles of Physical Optics", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Physical Optics", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.8-uuid';

-- Lesson 10.10.9: Wave-Particle Duality
UPDATE lessons
SET
    title = 'Wave-Particle Duality',
    slug = 'wave-particle-duality',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.9", "content": "Comprehensive explanation of Wave-Particle Duality including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.9", "problem": "Practice problem demonstrating key principles of Wave-Particle Duality", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Wave-Particle Duality", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.9-uuid';

-- Lesson 10.10.10: Modern Optical Applications
UPDATE lessons
SET
    title = 'Modern Optical Applications',
    slug = 'modern-optics-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 10.10.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 10 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 10.10.10", "content": "Comprehensive explanation of Modern Optical Applications including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 10.10.10", "problem": "Practice problem demonstrating key principles of Modern Optical Applications", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Modern Optical Applications", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 10.10.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 10.10.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 10.10.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch10-l10.10-uuid';

-- =====================================================
-- END OF CHAPTER 10
-- =====================================================