-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 1: ELECTRIC CHARGE AND COULOMB'S LAW
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 1.1.1: Electric Charge and Quantization
UPDATE lessons
SET
    title = 'Electric Charge and Quantization',
    slug = 'electric-charge-quantization',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.1", "content": "Comprehensive explanation of Electric Charge and Quantization including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.1", "problem": "Practice problem demonstrating key principles of Electric Charge and Quantization", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Charge and Quantization", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.1-uuid';

-- Lesson 1.1.2: Conductors and Insulators
UPDATE lessons
SET
    title = 'Conductors and Insulators',
    slug = 'conductors-insulators',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.2", "content": "Comprehensive explanation of Conductors and Insulators including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.2", "problem": "Practice problem demonstrating key principles of Conductors and Insulators", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Conductors and Insulators", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.2-uuid';

-- Lesson 1.1.3: Charging Methods
UPDATE lessons
SET
    title = 'Charging Methods',
    slug = 'charging-methods',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.3", "content": "Comprehensive explanation of Charging Methods including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.3", "problem": "Practice problem demonstrating key principles of Charging Methods", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Charging Methods", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.3-uuid';

-- Lesson 1.1.4: Coulomb's Law
UPDATE lessons
SET
    title = 'Coulomb's Law',
    slug = 'coulombs-law',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.4", "content": "Comprehensive explanation of Coulomb''s Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.4", "problem": "Practice problem demonstrating key principles of Coulomb''s Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Coulomb''s Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.4-uuid';

-- Lesson 1.1.5: Superposition Principle
UPDATE lessons
SET
    title = 'Superposition Principle',
    slug = 'superposition-principle',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.5", "content": "Comprehensive explanation of Superposition Principle including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.5", "problem": "Practice problem demonstrating key principles of Superposition Principle", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Superposition Principle", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.5-uuid';

-- Lesson 1.1.6: Electric Field Basics
UPDATE lessons
SET
    title = 'Electric Field Basics',
    slug = 'electric-field-basics',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.6", "content": "Comprehensive explanation of Electric Field Basics including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.6", "problem": "Practice problem demonstrating key principles of Electric Field Basics", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Field Basics", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.6-uuid';

-- Lesson 1.1.7: Field Lines Visualization
UPDATE lessons
SET
    title = 'Field Lines Visualization',
    slug = 'field-lines-visualization',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.7", "content": "Comprehensive explanation of Field Lines Visualization including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.7", "problem": "Practice problem demonstrating key principles of Field Lines Visualization", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Field Lines Visualization", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.7-uuid';

-- Lesson 1.1.8: Electric Dipoles
UPDATE lessons
SET
    title = 'Electric Dipoles',
    slug = 'electric-dipoles',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.8", "content": "Comprehensive explanation of Electric Dipoles including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.8", "problem": "Practice problem demonstrating key principles of Electric Dipoles", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Dipoles", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.8-uuid';

-- Lesson 1.1.9: Torque on Dipoles in Fields
UPDATE lessons
SET
    title = 'Torque on Dipoles in Fields',
    slug = 'dipole-torque',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.9", "content": "Comprehensive explanation of Torque on Dipoles in Fields including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.9", "problem": "Practice problem demonstrating key principles of Torque on Dipoles in Fields", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Torque on Dipoles in Fields", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.9-uuid';

-- Lesson 1.1.10: Applications of Electrostatics
UPDATE lessons
SET
    title = 'Applications of Electrostatics',
    slug = 'electrostatics-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 1.1.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 1 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 1.1.10", "content": "Comprehensive explanation of Applications of Electrostatics including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 1.1.10", "problem": "Practice problem demonstrating key principles of Applications of Electrostatics", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications of Electrostatics", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 1.1.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 1.1.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 1.1.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch1-l1.10-uuid';

-- =====================================================
-- END OF CHAPTER 1
-- =====================================================