-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 2: ELECTRIC FIELD
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 2.2.1: Electric Field Definition
UPDATE lessons
SET
    title = 'Electric Field Definition',
    slug = 'electric-field-definition',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.1", "content": "Comprehensive explanation of Electric Field Definition including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.1", "problem": "Practice problem demonstrating key principles of Electric Field Definition", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Field Definition", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.1-uuid';

-- Lesson 2.2.2: Field of Point Charges
UPDATE lessons
SET
    title = 'Field of Point Charges',
    slug = 'field-point-charges',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.2", "content": "Comprehensive explanation of Field of Point Charges including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.2", "problem": "Practice problem demonstrating key principles of Field of Point Charges", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Field of Point Charges", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.2-uuid';

-- Lesson 2.2.3: Continuous Charge Distributions
UPDATE lessons
SET
    title = 'Continuous Charge Distributions',
    slug = 'continuous-charge-distributions',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.3", "content": "Comprehensive explanation of Continuous Charge Distributions including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.3", "problem": "Practice problem demonstrating key principles of Continuous Charge Distributions", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Continuous Charge Distributions", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.3-uuid';

-- Lesson 2.2.4: Dipole Fields in Detail
UPDATE lessons
SET
    title = 'Dipole Fields in Detail',
    slug = 'dipole-fields-detail',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.4", "content": "Comprehensive explanation of Dipole Fields in Detail including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.4", "problem": "Practice problem demonstrating key principles of Dipole Fields in Detail", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Dipole Fields in Detail", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.4-uuid';

-- Lesson 2.2.5: Gauss's Law
UPDATE lessons
SET
    title = 'Gauss's Law',
    slug = 'gauss-law',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.5", "content": "Comprehensive explanation of Gauss''s Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.5", "problem": "Practice problem demonstrating key principles of Gauss''s Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Gauss''s Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.5-uuid';

-- Lesson 2.2.6: Applications of Gauss's Law
UPDATE lessons
SET
    title = 'Applications of Gauss's Law',
    slug = 'gauss-law-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.6", "content": "Comprehensive explanation of Applications of Gauss''s Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.6", "problem": "Practice problem demonstrating key principles of Applications of Gauss''s Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications of Gauss''s Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.6-uuid';

-- Lesson 2.2.7: Conductors in Equilibrium
UPDATE lessons
SET
    title = 'Conductors in Equilibrium',
    slug = 'conductors-equilibrium',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.7", "content": "Comprehensive explanation of Conductors in Equilibrium including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.7", "problem": "Practice problem demonstrating key principles of Conductors in Equilibrium", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Conductors in Equilibrium", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.7-uuid';

-- Lesson 2.2.8: Electric Flux
UPDATE lessons
SET
    title = 'Electric Flux',
    slug = 'electric-flux',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.8", "content": "Comprehensive explanation of Electric Flux including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.8", "problem": "Practice problem demonstrating key principles of Electric Flux", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Electric Flux", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.8-uuid';

-- Lesson 2.2.9: Gaussian Surfaces
UPDATE lessons
SET
    title = 'Gaussian Surfaces',
    slug = 'gaussian-surfaces',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.9", "content": "Comprehensive explanation of Gaussian Surfaces including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.9", "problem": "Practice problem demonstrating key principles of Gaussian Surfaces", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Gaussian Surfaces", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.9-uuid';

-- Lesson 2.2.10: Advanced Field Calculations
UPDATE lessons
SET
    title = 'Advanced Field Calculations',
    slug = 'advanced-field-calculations',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 2.2.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 2 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 2.2.10", "content": "Comprehensive explanation of Advanced Field Calculations including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 2.2.10", "problem": "Practice problem demonstrating key principles of Advanced Field Calculations", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Advanced Field Calculations", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 2.2.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 2.2.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 2.2.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch2-l2.10-uuid';

-- =====================================================
-- END OF CHAPTER 2
-- =====================================================