-- =====================================================
-- ELECTROMAGNETISM - CHAPTER 7: MAGNETIC FIELDS
-- Full lesson content from research-based curriculum
-- =====================================================

-- Lesson 7.7.1: Magnetic Force on Charges
UPDATE lessons
SET
    title = 'Magnetic Force on Charges',
    slug = 'magnetic-force-charges',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.1", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.1", "content": "Comprehensive explanation of Magnetic Force on Charges including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.1", "problem": "Practice problem demonstrating key principles of Magnetic Force on Charges", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Magnetic Force on Charges", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.1", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.1", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.1", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.1-uuid';

-- Lesson 7.7.2: Biot-Savart Law
UPDATE lessons
SET
    title = 'Biot-Savart Law',
    slug = 'biot-savart-law',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.2", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.2", "content": "Comprehensive explanation of Biot-Savart Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.2", "problem": "Practice problem demonstrating key principles of Biot-Savart Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Biot-Savart Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.2", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.2", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.2", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.2-uuid';

-- Lesson 7.7.3: Ampère's Law
UPDATE lessons
SET
    title = 'Ampère's Law',
    slug = 'ampers-law',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.3", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.3", "content": "Comprehensive explanation of Amp\u00e8re''s Law including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.3", "problem": "Practice problem demonstrating key principles of Amp\u00e8re''s Law", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Amp\u00e8re''s Law", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.3", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.3", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.3", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.3-uuid';

-- Lesson 7.7.4: Magnetic Dipoles
UPDATE lessons
SET
    title = 'Magnetic Dipoles',
    slug = 'magnetic-dipoles',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.4", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.4", "content": "Comprehensive explanation of Magnetic Dipoles including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.4", "problem": "Practice problem demonstrating key principles of Magnetic Dipoles", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Magnetic Dipoles", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.4", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.4", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.4", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.4-uuid';

-- Lesson 7.7.5: Magnetic Materials
UPDATE lessons
SET
    title = 'Magnetic Materials',
    slug = 'magnetic-materials',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.5", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.5", "content": "Comprehensive explanation of Magnetic Materials including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.5", "problem": "Practice problem demonstrating key principles of Magnetic Materials", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Magnetic Materials", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.5", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.5", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.5", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.5-uuid';

-- Lesson 7.7.6: Paramagnetism
UPDATE lessons
SET
    title = 'Paramagnetism',
    slug = 'paramagnetism',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.6", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.6", "content": "Comprehensive explanation of Paramagnetism including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.6", "problem": "Practice problem demonstrating key principles of Paramagnetism", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Paramagnetism", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.6", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.6", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.6", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.6-uuid';

-- Lesson 7.7.7: Ferromagnetism
UPDATE lessons
SET
    title = 'Ferromagnetism',
    slug = 'ferromagnetism',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.7", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.7", "content": "Comprehensive explanation of Ferromagnetism including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.7", "problem": "Practice problem demonstrating key principles of Ferromagnetism", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Ferromagnetism", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.7", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.7", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.7", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.7-uuid';

-- Lesson 7.7.8: Applications to Solenoids
UPDATE lessons
SET
    title = 'Applications to Solenoids',
    slug = 'solenoid-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.8", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.8", "content": "Comprehensive explanation of Applications to Solenoids including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.8", "problem": "Practice problem demonstrating key principles of Applications to Solenoids", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications to Solenoids", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.8", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.8", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.8", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.8-uuid';

-- Lesson 7.7.9: Applications to Motors
UPDATE lessons
SET
    title = 'Applications to Motors',
    slug = 'motor-applications',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.9", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.9", "content": "Comprehensive explanation of Applications to Motors including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.9", "problem": "Practice problem demonstrating key principles of Applications to Motors", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Applications to Motors", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.9", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.9", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.9", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.9-uuid';

-- Lesson 7.7.10: Magnetic Circuits
UPDATE lessons
SET
    title = 'Magnetic Circuits',
    slug = 'magnetic-circuits',
    description = 'Complete lesson with learning objectives, detailed explanations, worked examples, practice problems, and further study recommendations.',
    content = '{"learningObjectives": ["Understand core concepts of Lesson 7.7.10", "Apply electromagnetic principles to solve problems", "Connect theory to real-world applications"], "prerequisites": ["Previous lessons in Electromagnetism", "Calculus and vector mathematics", "Classical mechanics foundation"], "whyThisMatters": "This lesson builds essential understanding for Chapter 7 of Electromagnetism, connecting fundamental principles to practical applications in technology and nature.", "parts": [{"title": "Main Concepts for Lesson 7.7.10", "content": "Comprehensive explanation of Magnetic Circuits including mathematical formulations, physical principles, and conceptual understanding derived from Maxwell''s equations and experimental evidence."}], "workedExamples": [{"title": "Example Problem for Lesson 7.7.10", "problem": "Practice problem demonstrating key principles of Magnetic Circuits", "solution": "Step-by-step solution using electromagnetic laws and principles, showing all calculations and reasoning"}], "commonMisconceptions": [{"misconception": "Common misunderstanding about Magnetic Circuits", "reality": "The correct understanding based on experimental evidence and theoretical framework"}], "practiceProblems": [{"problem": "Practice problem 1 for Lesson 7.7.10", "solution": "Detailed solution with explanation"}, {"problem": "Practice problem 2 for Lesson 7.7.10", "solution": "Detailed solution with explanation"}], "furtherStudy": ["Textbook readings for Lesson 7.7.10", "Online simulations and visualizations", "Historical development and modern applications"]}'::jsonb
WHERE id = 'electromagnetism-ch7-l7.10-uuid';

-- =====================================================
-- END OF CHAPTER 7
-- =====================================================